sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        f0DIpCLxkSvn1FBmA50OlGgMhMFrlJrl+YoHCCPtnRYTd2BiCceXDS92E/26C+RHuVJtC0qBGylexFJWk9Uu2VfXSGKzZwinKjF0RZCXhzMQDestUvTeFCnq8bEtxhvzesiaHGrJTUyDYyjkPJrrw6mMlydwX9Bv/+VP6Fk7BNQ1XeDVt/DvZ5j+IcFFlbG56IY9bNR8rTDolPQjHNZZQN5nWJjD4kSCdbN/M6whr7Eevbc8yOTcCrsBpLqmTEwSEAaZAKZdaAOl+Z+oaI6PffKafZCtAuDp1lBZT7xUCf4aumktzFnq7I4cJDT/wBzsfVFIg+itbR8M+DR7UUeUvSY7PtiWJTJFROeH2rXguYNVBoJPyWPx1v7Nl1OFjov4ec3EkLEDpTcruC4zhOfYxVaQqVluqnPL77QLk4MFdEAbhpjoYotY09tG9oLsY7HxUZmChh8VCBSaXwTn5EDhT9Cg8MYwzvKdG8BJZubrgtmrDGMTM++rhPjFtjot7UM4wqRWYUCW/oJH3nwmWiQVyBz4gDEa8uBLgFDzleSVx+xQsdOoZ8srevtEEboNrU5G8ETbiw2C4pPiL3krUgm/ejtYhzsi5U1qPkFRynXXIH69qBqvMkoXq1NlvmQkvBOohFoUCirBue9a/w6lfYPS17Pc64g7KMfiENpuf7ZM9LM=
    - secure: >-
        G71enTHS8qOTjrGt+39Ap6MfdrtZ39CbEA3lb77ztm22k8dUDoBS9My5/QJJAJPO2GhUtQzTWsuD4MkkAJCS1rFfmbAW8iXR2X0aD185UVLiyUOARBT6qmYrJrLV7LSQDkOgQX7ECsbSYJ7Aq+p/d6QLJ7evSQNRTSFnKsqKNUUYFdQASYL5QMr7E6nwTgd6Pi5GZD8beOYgid6Tw0iWsQVR4kSRXuHhrk7ZSbOBT+c458Z3m1ujVbqx1k2djnZV63tQMFR4WGvGPRMyxQS9IUosxFnZRu/3zA52FmOyjU3lUChgdQVVTaV+34eHjqUpdLsThmHYrMrwxwKHi+tN0iRc0ng5BlQVUvW3IwvOy/BL9dw/9SQtu0uquUzTvPr0lar1UwCrYR5MSzHmC7DNNHHcBNrSatRBLPoDHE36ccjXcehA+7QthKY7/SQSQMzwYSqS35+koRT1o75U+CWTgl3XVVnuWYpv+vipdy+Dr6Hg+zQz3pCVDWBrfPGbf24lSvHCAj9CPlxJO2CZJ51udY4GN3j8t8+iyXfFxU8WATTgqfLsRpKsTeWFFXjLQMVW0PZdOKjUZEjhmUQafGSDjaTj+n9wLwpaDRzWjGOCLSJoM/TOi3SGg533n+TMHwkGFjWmopcnwFxq+bIHklettSTRMj9x9Ag+fl5bCimn5V0=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
